Fix fringe customization
Alexander-Miller/treemacs pull request #715
Opened 2020-08-27 06:03 UTC by sebastiencs

- Fix display property of the fringe overlay 
  This worked because the defcustom and the bitmap were on the same
  symbol.
  The fringe property is expecting the symbol of the bitmap, so this
  ignored the value of the defcustom.

- Make the default fringe bitmap bigger and fix type of the defcustom
  The default bitmap didn't fill the whole line in my config
  Not sure what was the `:options` for ?

2020-08-29 09:15 UTC, Alexander-Miller requested changes
LGTM. All that's missing is to prefix the commit messages with `[Fringe Indicator]`.

2020-08-29 18:32 UTC, sebastiencs commented
@Alexander-Miller Done

2020-08-30 09:20 UTC, Alexander-Miller approved these changes

2020-08-30 09:20 UTC, Alexander-Miller commented
:+1:

2020-08-30 09:21 UTC, merged