Tab bar mode
Alexander-Miller/treemacs pull request #903
Opened 2022-01-31 16:05 UTC by aaronjensen

Adds support for `tab-bar-mode` based on the support for perspectives. From my limited testing so far, it appears to work well and as I'd expect. 

Fixes #901 
Fixes #902

2022-02-08 21:54 UTC, cmccloud commented
Would love to see this get merged.

2022-02-10 19:44 UTC, aaronjensen commented
This has been updated to use the fix from #902

2022-02-14 21:22 UTC, Alexander-Miller requested changes

2022-02-14 21:22 UTC, Alexander-Miller commented on README.org
> +(use-package treemacs-tab-bar ;;treemacs-tab-bar if you use tab-bar-mode
The indentation isn't quite right, it should be 2 spaces further to the right.

2022-02-14 21:22 UTC, Alexander-Miller commented on README.org
> + - emacs >= 26.1 (>= 27.1 for tab-bar)
New module will need a new tag line for commit messages. Let's go with `[Tab Bar]` on this one.

2022-02-15 11:02 UTC, aaronjensen commented
@Alexander-Miller thank you, updated.

2022-02-16 19:23 UTC, Alexander-Miller approved these changes

2022-02-16 19:23 UTC, merged

2022-02-16 19:49 UTC, Alexander-Miller commented
Next stop: melpa https://github.com/melpa/melpa/pull/7913