Paste here
Alexander-Miller/treemacs pull request #995
Opened 2022-12-06 23:38 UTC by andyjda

See [issue 994](https://github.com/Alexander-Miller/treemacs/issues/994)

2022-12-22 13:34 UTC, Alexander-Miller requested changes

2022-12-22 13:34 UTC, Alexander-Miller commented on src/elisp/treemacs-mouse-interface.el
> +              (identifier)
Indentation shouldn't change here. The latest commit adds a .dir-locals file that should preclude unwanted diffs like this.

2022-12-22 13:34 UTC, Alexander-Miller commented on src/elisp/treemacs-mouse-interface.el
> +(defun treemacs--paste-point-to-minibuffer ()
This command is public, so its name needs to have only one dash.

It is also not strictly part of the mouse interface, but is a more general utility, so it should be part of treemacs-interface.el. 

The name should also change to paste-path-at-point-to-minibuffer so it's clear what exactly it does.

2022-12-22 13:34 UTC, Alexander-Miller commented on src/elisp/treemacs-mouse-interface.el
> +This is used by the \"Paste here\" button,
Doc should specify it's the button from the mouse menu.

2022-12-22 13:34 UTC, Alexander-Miller commented on src/elisp/treemacs-mouse-interface.el
> +    (switch-to-minibuffer)
That's for interactive use only. Use `(select-window (minibuffer-window))`

2022-12-22 13:34 UTC, Alexander-Miller commented on src/elisp/treemacs-mouse-interface.el
> +    (mark-whole-buffer)
Same here, use `(delete-region (point-min) (point-max))` or `delete-minibuffer-contents`.

2022-12-22 13:34 UTC, Alexander-Miller commented on src/elisp/treemacs-mouse-interface.el
> +  (message "copied from treemacs"))
`treemacs-log`

2022-12-22 13:34 UTC, Alexander-Miller commented on src/elisp/treemacs-mouse-interface.el
> +                 :visible ,(string-match-p "\\(\\(Move\\)\\|\\(Copy\\)\\) to: " (or (minibuffer-prompt) ""))]
`(rx (or "Copy" "Move") " to:")`

2022-12-22 13:34 UTC, Alexander-Miller commented on src/elisp/treemacs-mouse-interface.el
> +                ("New"
Finally at the end the commits need to be squashed and the commit message prefixed with `[Interface]`.

2022-12-23 02:42 UTC, andyjda commented
applied these changes; let me know if I missed something or if you need anything else from me :)

2022-12-23 16:20 UTC, Alexander-Miller commented
Almost there, only some nitpicks left.

2022-12-28 14:15 UTC, andyjda commented
Do you need me to make any additional changes? I thought I fixed all issues pointed out in your comments; let me know if I'm missing something or if there are additional edits needed

2022-12-29 12:45 UTC, Alexander-Miller requested changes

2022-12-29 12:45 UTC, Alexander-Miller commented
Looks like I forgot to submit my review. You should see the new comments now.

2023-01-10 04:18 UTC, andyjda commented
Thanks for the review, just pushed the changes :)
Let me know if there's anything else I'm missing

2023-03-08 23:33 UTC, andyjda commented
@Alexander-Miller any update on this?

2023-05-10 05:46 UTC, Alexander-Miller commented
> any update on this?

Apparently the update is that I sometimes forget to press the "Review Changes" button so my comments never show up. It doesn't help that github shows me that changes have been requested already. My bad :(

![c](https://github.com/Alexander-Miller/treemacs/assets/5951157/4220aad2-60ec-400c-91ef-8398fff6ef41)

Anyway, no more delays now, I'll take care about my findings myself and merge in a day or two.

2023-05-10 06:42 UTC, Alexander-Miller approved these changes

2023-05-10 16:44 UTC, merged

2023-05-10 16:44 UTC, Alexander-Miller commented
All done now. I've moved a few things around, let me know if anything is missing.

2023-05-14 13:25 UTC, andyjda commented
looks perfect! Thank you